first_name = input("What is your name?")
last_name = input("What is your last_name?")
age = int(input("How old are you?"))
height = float(input("What is your height?"))
country = input("Which country do you live in?")
print ("========== PROFIL ==========")
print ("First_name:",first_name)
print ("Last_name:",last_name)
print ("Age:",age)
print ("Height:",height)
print ("Country:",country)
print ("Next year you will be",age+1)
